name: Sync Notion to GitHub
on:
  schedule:
    - cron: '0 0 * * *' # Syncs automatically every day
  workflow_dispatch: # Allows you to manually trigger it
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: notion-sync
        uses: YouXam/Notion-GitHub-Sync@v2
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
